// Package gatewayutil 提供 gateway 相关的工具函数。
// 原 github.com/streasure/util/gatewayutil 已在 util 仓库移除，本地化保留。
package gatewayutil

import (
	"fmt"
	"hash/fnv"
	"maps"
	"math/rand/v2"
	"sync/atomic"
	"time"
)

const (
	connIDPrefixBits  = 48
	connIDCounterZero = 20 // digits of math.MaxUint64
)

var (
	connIDCounter atomic.Uint64
	connIDPrefix  = newConnIDPrefix()
)

// newConnIDPrefix returns a random per-process prefix so IDs generated by
// different processes never collide.
func newConnIDPrefix() string {
	return fmt.Sprintf("%012x", rand.UintN(1<<connIDPrefixBits))
}

// GenerateConnectionID 生成唯一连接 ID：毫秒时间戳 + 进程随机前缀 + 全宽递增计数器
func GenerateConnectionID() string {
	return formatConnectionID(time.Now().UnixMilli(), connIDPrefix, connIDCounter.Add(1))
}

// formatConnectionID formats the ID parts. The counter keeps its full width so
// it never wraps into an ID issued earlier in the same millisecond.
func formatConnectionID(ms int64, prefix string, counter uint64) string {
	return fmt.Sprintf("%d%s%0*d", ms, prefix, connIDCounterZero, counter)
}

// GetString 从 map 中安全取 string 值
func GetString(m map[string]any, key string) string {
	if v, ok := m[key]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

// GetInt 从 map 中安全取 int 值
func GetInt(m map[string]any, key string) int {
	if v, ok := m[key]; ok {
		switch x := v.(type) {
		case int:
			return x
		case float64:
			return int(x)
		}
	}
	return 0
}

// GetFloat 从 map 中安全取 float64 值
func GetFloat(m map[string]any, key string) float64 {
	if v, ok := m[key]; ok {
		switch x := v.(type) {
		case float64:
			return x
		case int:
			return float64(x)
		}
	}
	return 0
}

// ParseDurationDefault 解析时间字符串，失败返回默认值
func ParseDurationDefault(s string, def time.Duration) time.Duration {
	if s == "" {
		return def
	}
	if d, err := time.ParseDuration(s); err == nil {
		return d
	}
	return def
}

// SimpleHash FNV-1a 哈希
func SimpleHash(s string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h.Sum32()
}

// CopyMap 浅拷贝 map
func CopyMap(m map[string]string) map[string]string {
	out := make(map[string]string, len(m))
	maps.Copy(out, m)
	return out
}

// MaxInt 返回较大值
func MaxInt(a, b int) int {
	return max(a, b)
}
