package protobuf

const (
	RouteHandshake         = "handshake"
	RouteLogin             = "login"
	RoutePing              = "ping"
	RoutePong              = "pong"
	RouteTest              = "test"
	RouteTestResult        = "testResult"
	RouteVersion           = "version"
	RouteGetConnections    = "getConnections"
	RouteBroadcast         = "broadcast"
	RouteHealth            = "health"
	RouteAPIDocs           = "api-docs"
	RouteError             = "error"
	RouteEcho              = "echo"
	RouteMessage           = "message"
	RouteKick              = "kick"
	RouteTimeout           = "timeout"
	RouteHandshakeResponse = "handshake_response"
	RouteQueueTest         = "queueTest"
	RouteAddWhitelist      = "addWhitelist"
	RouteRemoveWhitelist   = "removeWhitelist"
	RouteGetWhitelist      = "getWhitelist"
	RouteAddBlacklist      = "addBlacklist"
	RouteRemoveBlacklist   = "removeBlacklist"
	RouteGetBlacklist      = "getBlacklist"

	RouteServerKick                = "server.kick"
	RouteServerJoinGroup           = "server.join_group"
	RouteServerLeaveGroup          = "server.leave_group"
	RouteServerJoinGroupByUser     = "server.join_group_by_user"
	RouteServerLeaveGroupByUser    = "server.leave_group_by_user"
	RouteServerCreateGroup         = "server.create_group"
	RouteServerDeleteGroup         = "server.delete_group"
	RouteServerSendToGroup         = "server.send_to_group"
	RouteServerGetGroupInfo        = "server.get_group_info"
	RouteServerPlayerOnline        = "server.playerOnline"
	RouteServerPlayerOffline       = "server.playerOffline"
	RouteServerPlayerMoved         = "server.playerMoved"
	RouteServerChat                = "server.chat"
	RouteServerPush                = "server.push"
	RouteServerAnnouncement        = "server.announcement"
	RouteServerAnnounce            = "server.announce"
	RouteServerRoomPlayerJoined    = "server.room.playerJoined"
	RouteServerRoomPlayerLeft      = "server.room.playerLeft"
	RouteServerTeamMemberJoined    = "server.team.memberJoined"
	RouteServerTeamMemberLeft      = "server.team.memberLeft"
	RouteServerDamageNotify        = "server.damageNotify"
	RouteServerAttackBroadcast     = "server.attackBroadcast"

	RoutePlayerLogin        = "player.login"
	RoutePlayerHeartbeat    = "player.heartbeat"
	RoutePlayerMove         = "player.move"
	RoutePlayerChat         = "player.chat"
	RoutePlayerAttack       = "player.attack"
	RoutePlayerUseItem      = "player.useItem"
	RoutePlayerQueryStatus  = "player.queryStatus"
	RoutePlayerQueryOnline  = "player.queryOnline"

	RouteRoomJoin  = "room.join"
	RouteRoomLeave = "room.leave"
	RouteRoomInfo  = "room.info"

	RouteTeamCreate = "team.create"
	RouteTeamJoin   = "team.join"
	RouteTeamLeave  = "team.leave"
	RouteTeamInfo   = "team.info"
)
