listenAddr: "0.0.0.0"
listenPort: "50052"
advertiseAddr: "localhost:50052"
serverId: "logic-1"
serverType: "Logic"
serviceName: "logic"
zone: "default"
etcdEndpoint: "http://127.0.0.1:2379"
etcdEndpoints: ["http://127.0.0.1:2379"]
etcdServicePrefix: "/services"
etcdLeaseTTL: "10s"
heartbeatInterval: 3s
heartbeatTTL: 10s
grpcWindowSize: 67108864
grpcMaxMessageSize: 4194304
dispatchWorkers: 24
streamSendChSize: 1048576
passthrough: false
